<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="1.2.0" name="Basic" tilewidth="16" tileheight="16" tilecount="60" columns="10">
 <image source="../UNI/2nd Año/Desarrollo de videojuegos/Global_Platform_Game Assest/Tileset.png" width="160" height="96"/>
 <terraintypes>
  <terrain name="Ground" tile="-1"/>
  <terrain name="Rock" tile="-1"/>
  <terrain name="Grass" tile="-1"/>
  <terrain name="Bush" tile="-1"/>
  <terrain name="Spikes" tile="-1"/>
  <terrain name="Fence" tile="0"/>
  <terrain name="Bridge" tile="0"/>
 </terraintypes>
 <tile id="0" terrain=",,,0"/>
 <tile id="1" terrain=",,0,0"/>
 <tile id="2" terrain=",,0,"/>
 <tile id="3" terrain=",,0,0"/>
 <tile id="4" terrain="0,0,0,"/>
 <tile id="5" terrain="0,0,,0"/>
 <tile id="6" terrain=",0,0,0"/>
 <tile id="7" terrain="0,,,0"/>
 <tile id="10" terrain=",0,,0"/>
 <tile id="11" terrain="0,0,0,0"/>
 <tile id="12" terrain="0,,0,"/>
 <tile id="13" terrain="0,0,0,0"/>
 <tile id="14" terrain="0,,0,0"/>
 <tile id="15" terrain=",0,0,"/>
 <tile id="20" terrain=",0,,"/>
 <tile id="21" terrain="0,0,,"/>
 <tile id="22" terrain="0,,,"/>
 <tile id="23" terrain="0,0,0,0"/>
 <tile id="26" terrain=",2,,"/>
 <tile id="27" terrain="2,2,,"/>
 <tile id="28" terrain="2,2,,"/>
 <tile id="29" terrain="2,,,"/>
 <tile id="30" terrain=",,,1"/>
 <tile id="31" terrain=",,1,1"/>
 <tile id="32" terrain=",,1,"/>
 <tile id="33" terrain="1,1,1,"/>
 <tile id="34" terrain="1,1,,1"/>
 <tile id="36" terrain=",5,,"/>
 <tile id="37" terrain="5,5,,"/>
 <tile id="38" terrain="5,5,,"/>
 <tile id="39" terrain="5,,,"/>
 <tile id="40" terrain=",1,,1"/>
 <tile id="41" terrain="1,1,1,1"/>
 <tile id="42" terrain="1,,1,"/>
 <tile id="43" terrain="1,,1,1"/>
 <tile id="44" terrain=",1,1,1"/>
 <tile id="46" terrain="6,,,"/>
 <tile id="47" terrain="6,6,,"/>
 <tile id="48" terrain=",6,,"/>
 <tile id="49" terrain="4,4,4,4"/>
 <tile id="50" terrain=",1,,"/>
 <tile id="51" terrain="1,1,,"/>
 <tile id="52" terrain="1,,,"/>
 <tile id="53" terrain="1,,,1"/>
 <tile id="54" terrain=",1,1,"/>
 <tile id="55" terrain=",3,,"/>
 <tile id="56" terrain="3,3,,"/>
 <tile id="57" terrain="3,,,"/>
</tileset>
